### ISSUE TITLE
A Better Implementation

### ISSUE THREAD

**Issue by xialvjun** [Astrocoders/epitath#23]
```ts
import immutagen from "immutagen";

const compose = ({ next, value }) =>
  next
    ? React.cloneElement(value, null, (...args) => compose(next(args)))
    : value;

export function epitath(gen_fn, _this) {
  if (arguments.length < 2) {
    _this = this;
  }
  gen_fn = immutagen(gen_fn.bind(_this));
  return (...args) => compose(gen_fn(...args));
}
```

That's all!!!
**It can avoid creating new `Component` in every `render`.**

**Comment by grsabreu** [comment]
Hey @xialvjun, thanks for your suggestion.
Could you explain why have you decided to add this new argument `_this` to the function arguments? 
Also I think this implementation drops class-based components support

Also could you provide a codesandbox link with demos so we can test it quickly?

**Comment by xialvjun** [comment]
@grsabreu 
https://codesandbox.io/s/llk019z0nl

**Comment by eliperelman** [comment]
> Also I think this implementation drops class-based components support

This has also not been addressed.

**Comment by xialvjun** [comment]
what do you mean by `drops class-based components support`?

**Comment by grsabreu** [comment]
@eliperelman we delayed indeed to release, it was released now at 1.0.0-beta.2. Sorry the delay.

**Comment by grsabreu** [comment]
@xialvjun https://codesandbox.io/s/n5oj71z44l

**Comment by grsabreu** [comment]
Also, we add a "Epitath" wrapper in the component to make easier to see this in the dev tools, see #1

**Comment by xialvjun** [comment]
Well, I don't know how to add class-based components support and I don't care about it. Pure Generator Component has meet my needs.

And I didn't add "Epitath" wrapper because this is just a issue, not a PR.
